name: ci

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install
        env:
          LIHBR_APEX: ${{ secrets.LIHBR_APEX }}

      - name: Lint
        run: pnpm lint

  test:
    runs-on: ${{ matrix.os }}
    name: test (os ${{ matrix.os }}, node ${{ matrix.node }})

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install
        env:
          LIHBR_APEX: ${{ secrets.LIHBR_APEX }}

      - name: Typecheck
        run: pnpm typecheck

      # - name: Unit
      #   run: pnpm unit

      # - name: Build
      #   run: pnpm build
